title: Weixuyang's Homepage
page-top-title: Weixuyang
top-section-bg-text: School of Software Engineering, UESTC
home-subtitle: Weixuyang&ensp;|&ensp;
copyright-text: '&copy; Weixuyang 2022-2025. All Rights Reserved.'
