title: Weixuyang's Homepage
page-top-title: Weixuyang
top-section-bg-text: Students enrolled in the School of Software Engineering, UESTC
home-subtitle: Weixuyang&ensp;|&ensp;
copyright-text: '&copy; Weixuyang 2024-2025. All Rights Reserved.'
